### ISSUE TITLE
X API Token

### ISSUE THREAD

**Issue by hech1** [ZoeyVid/aida-price-checker#29]
Hi Zoey,

do you know where I can find the X API token? Should I simply go to the Aida.de website and look for it using the Developer Tools? I couldn’t find it there (or maybe I’m just blind 😄).

Thanks a lot for your support!

Cheers,
Chris

**Comment by Zoey2936** [comment]
Hi, if open the network page in the developer tools of your browser (F12) and open the cabine selection of a tour, then there will be requests to iris.cruise-api.aida.de and if you open this request you can find the token as a request header

**Comment by Zoey2936** [comment]
I peronally don't understand theese token since it does not expire and is valid on any ip

**Comment by hech1** [comment]
Hi Zoey,

Thanks for the clarification!

I noticed that the API request only appears when selecting the cabin—it doesn’t show up when simply searching for a trip, for example.

Thank you!
